=== roman-corgi/ctc-dip/schema/categorization.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
            elementFormDefault="unqualified"
            attributeFormDefault="unqualified">
  <!-- defines how the channels files are defined on disk for override -->
  <xs:complexType name="channels_type">
    <xs:annotation>
      <xs:documentation xml:lang="en">
        Define all of the channels files.
      </xs:documentation>
    </xs:annotation>
    <xs:all>
      <xs:element name="cal_a" type="rpn"/>
      <xs:element name="cal_absflux" type="rpn"/>
      <xs:element name="cal_badpixelmap" type="rpn"/>
      <xs:element name="cal_boresight" type="rpn"/>
      <xs:element name="cal_corethpt" type="rpn"/>
      <xs:element name="cal_darkpc" type="rpn"/>
      <xs:element name="cal_darksynth" type="rpn"/>
      <xs:element name="cal_darktrad" type="rpn"/>
      <xs:element name="cal_dispersionmodel" type="rpn"/>
      <xs:element name="cal_flatfield" type="rpn"/>
      <xs:element name="cal_polff" type="rpn"/>
      <xs:element name="cal_linespread" type="rpn"/>
      <xs:element name="cal_muellermatrix" type="rpn"/>
      <xs:element name="cal_ndfiltimg" type="rpn"/>
      <xs:element name="cal_ndfiltspec" type="rpn"/>
      <xs:element name="cal_pupil" type="rpn"/>
      <xs:element name="cal_wlzeropoint" type="rpn"/>
      <xs:element name="eng_a" type="rpn"/>
      <xs:element name="nfov_a" type="rpn"/>
      <xs:element name="nfov_nc" type="rpn"/>
      <xs:element name="nfov_pc" type="rpn"/>
      <xs:element name="pol_a" type="rpn"/>
      <xs:element name="pol_pc" type="rpn"/>
      <xs:element name="spec_a" type="rpn"/>
      <xs:element name="spec_nc" type="rpn"/>
      <xs:element name="spec_pc" type="rpn"/>
      <xs:element name="wfov_a" type="rpn"/>
      <xs:element name="wfov_nc" type="rpn"/>
      <xs:element name="wfov_pc" type="rpn"/>
    </xs:all>
  </xs:complexType>

  <xs:complexType name="operand_type">
    <xs:annotation>
      <xs:documentation xml:lang="en">
        Define what a list of in/ex-cludes are

        @keyword is the keyword from the primary header
        @operator is how the values should be checked against the header value

        value - an attempt will be made to case this value to what fits reports as the type of the value in the header like bool, complex, float, int, and str. Note that these are Python representation. Therefore the value in the xml file like <value>0</value> must give the correct result for bool(x) in Python if the value in the header is T/F which will report as a bool. Hopefully that makes any sense at all.
      </xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="value" minOccurs="1" maxOccurs="unbounded" type="xs:anyType"/>
    </xs:sequence>
    <xs:attribute default="false" name="not" type="xs:boolean" use="optional"/>
    <xs:attribute name="keyword" type="xs:normalizedString" use="required"/>
    <xs:attribute name="operator" type="set_operator" use="required"/>
  </xs:complexType>

  <xs:complexType name="rpn">
    <xs:annotation>
      <xs:documentation xml:lang="en">
        Each channel is made up includes rules and excludes rules.
      </xs:documentation>
      <xs:appinfo>
        <sch:pattern id="rpn-stack-validation" xmlns:sch="http://oclc.org">
          <sch:rule context="*[local-name()='channel' or @type='rpn' or type='rpn'] | rpn">
            <sch:let name="operands_count" value="count(operand)"/>
            <sch:let name="operators_count" value="count(operator)"/>
            <sch:assert test="$operands_count &gt; 0" role="error">
              An RPN sequence must contain at least one operand.
            </sch:assert>
            <sch:assert test="($operands_count - $operators_count) = 1" role="error">
              Invalid RPN sequence. The layout must resolve to exactly one final boolean value. 
              Current state: <sch:value-of select="$operands_count"/> operands and 
              <sch:value-of select="$operators_count"/> operators.
            </sch:assert>
          </sch:rule>
          <sch:rule context="*[operand or operator]/operator">
            <sch:let name="prev_operands" value="count(preceding-sibling::operand)"/>
            <sch:let name="prev_operators" value="count(preceding-sibling::operator)"/>
            <sch:let name="stack_depth_before" value="$prev_operands - $prev_operators"/>
            <sch:assert test="$stack_depth_before &gt;= 2" role="error">
              Stack underflow! The operator '<sch:value-of select="text()"/>' requires two active booleans on the stack. 
              Only <sch:value-of select="$stack_depth_before"/> value(s) are available.
            </sch:assert>
          </sch:rule>
        </sch:pattern>
      </xs:appinfo>
    </xs:annotation>
    <xs:sequence>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element name="operand" type="operand_type"/>
        <xs:element name="operator" type="logical_operator"/>
      </xs:choice>
    </xs:sequence>
  </xs:complexType>

  <xs:simpleType name="logical_operator">
    <xs:restriction base="xs:normalizedString">
      <xs:enumeration value="and"/>
      <xs:enumeration value="nand"/>
      <xs:enumeration value="nor"/>
      <xs:enumeration value="or"/>
      <xs:enumeration value="xnor"/>
      <xs:enumeration value="xor"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="set_operator">
    <xs:restriction base="xs:normalizedString">
      <xs:enumeration value="contains-all"/>
      <xs:enumeration value="contains-any"/>
      <xs:enumeration value="equals-all"/>
      <xs:enumeration value="equals-any"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:element name="channels">
    <xs:complexType>
      <xs:annotation>
        <xs:documentation xml:lang="en">
          This terrible construct is so that xjc can autodetect this as the
          root node for processing. Many things would be better but this is
          the most workable solution especially if the making of the binding
          code is automated in the pom. The only other real solution is to
          modify one of the classes generated by hand.
        </xs:documentation>
      </xs:annotation>
      <xs:complexContent>
        <xs:extension base="channels_type"/>
      </xs:complexContent>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== roman-corgi/ctc-dip/dip/base/categorization.xml
<channels
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/roman-corgi/ctc-dip/refs/heads/main/schema/categorization.xsd">
  <cal_a/>
  <cal_absflux/>
  <cal_badpixelmap>
    <operand keyword="VISTYPE" operator="equals-any">
      <value>-999</value>
      <value>N/A</value>
    </operand>
    <operand keyword="FRMTYPE" not="true" operator="equals-all">
      <value>ACQ</value>
    </operand>
    <operator>and</operator>
  </cal_badpixelmap>
  <cal_boresight>
    <operand keyword="VISTYPE" operator="equals-all">
      <value>CGIVST_CAL_BORESIGHT</value>
    </operand>
    <operand keyword="FRMTYPE" not="true" operator="equals-all">
      <value>ACQ</value>
    </operand>
    <operator>and</operator>
  </cal_boresight>
  <cal_corethpt>
    <operand keyword="VISTYPE" operator="equals-all">
      <value>CGIVST_CAL_CORETHRPT</value>
    </operand>
    <operand keyword="FRMTYPE" not="true" operator="equals-all">
      <value>ACQ</value>
    </operand>
    <operator>and</operator>
  </cal_corethpt>
  <cal_darkpc>
    <operand keyword="VISTYPE" operator="equals-all">
      <value>CGIVST_CAL_DRK</value>
    </operand>
    <operand keyword="FRMTYPE" not="true" operator="equals-all">
      <value>ACQ</value>
    </operand>
    <operator>and</operator>
    <operand keyword="PC_STAT" operator="equals-all">
      <value>photon-counted master dark</value>
    </operand>
    <operator>and</operator>
    <operand keyword="IS_SYNTH" operator="equals-all">
      <value>0</value>
    </operand>
    <operator>and</operator>
  </cal_darkpc>
  <cal_darksynth>
    <operand keyword="VISTYPE" operator="equals-all">
      <value>CGIVST_CAL_DRK</value>
    </operand>
    <operand keyword="FRMTYPE" not="true" operator="equals-all">
      <value>ACQ</value>
    </operand>
    <operator>and</operator>
    <operand keyword="PC_STAT" operator="equals-all">
      <value>analog master dark</value>
    </operand>
    <operator>and</operator>
    <operand keyword="IS_SYNTH" operator="equals-all">
      <value>1</value>
    </operand>
    <operator>and</operator>
  </cal_darksynth>
  <cal_darktrad>
    <operand keyword="VISTYPE" operator="equals-all">
      <value>CGIVST_CAL_DRK</value>
    </operand>
    <operand keyword="FRMTYPE" not="true" operator="equals-all">
      <value>ACQ</value>
    </operand>
    <operator>and</operator>
    <operand keyword="PC_STAT" operator="equals-all">
      <value>analog master dark</value>
    </operand>
    <operator>and</operator>
    <operand keyword="IS_SYNTH" operator="equals-all">
      <value>0</value>
    </operand>
    <operator>and</operator>
  </cal_darktrad>
  <cal_dispersionmodel>
     <operand keyword="VISTYPE" operator="equals-any">
      <value>CGIVST_CAL_SPEC_TGTREF</value>
    </operand>
    <operand keyword="FRMTYPE" not="true" operator="equals-all">
      <value>ACQ</value>
    </operand>
    <operator>and</operator>
    <operand keyword="FPAMNAME" operator="equals-any">
      <value>OPEN</value>
    </operand>
    <operator>and</operator>
  </cal_dispersionmodel>
  <cal_flatfield>
    <operand keyword="VISTYPE" operator="equals-any">
      <value>CGIVST_CAL_FLAT</value>
    </operand>
    <operand keyword="DPAMNAME" operator="equals-any" not="true">
      <value>POL0</value>
      <value>POL45</value>
    </operand>
    <operator>and</operator>
  </cal_flatfield>
  <cal_polff>
    <operand keyword="VISTYPE" operator="equals-any">
      <value>CGIVST_CAL_FLAT</value>
    </operand>
    <operand keyword="DPAMNAME" operator="equals-any">
      <value>POL0</value>
      <value>POL45</value>
    </operand>
    <operator>and</operator>
  </cal_polff>
  <cal_linespread/>
  <cal_muellermatrix/>
  <cal_ndfiltimg/>
  <cal_ndfiltspec/>
  <cal_pupil>
    <operand keyword="VISTYPE" operator="equals-all">
      <value>CGIVST_CAL_PUPIL_IMAGING</value>
    </operand>
    <operand keyword="FRMTYPE" not="true" operator="equals-all">
      <value>ACQ</value>
    </operand>
    <operator>and</operator>
  </cal_pupil>
  <cal_wlzeropoint/>
  <eng_a>
    <operand keyword="VISTYPE" operator="equals-any">
      <value>CGIVST_ENG_OTA_WVFRNT</value>
      <value>CGIVST_ENG_PFAC</value>
      <value>CGIVST_ENG_PUPILCAL</value>
      <value>CGIVST_ENG_IMAGECAL</value>
      <value>CGIVST_ENG_GENERIC_RASTER</value>
      <value>CGIVST_TDD_SETUP_HOWFSC</value>
      <value>CGIVST_TDD_OBS_HOWFSC</value>
      <value>CGIVST_UTI_GENERIC_STAR</value>
      <value>CGIVST_UTI_POINT_REFINE</value>
    </operand>
    <operand keyword="DPAMNAME" operator="contains-any">
      <value>IMAGING</value>
      <value>PUPIL</value>
      <value>DEFOCUS1</value>
      <value>DEFOCUS2</value>
      <value>DEFOCUS3</value>
      <value>DEFOCUS4</value>
    </operand>
    <operand keyword="FRMTYPE" not="true" operator="equals-any">
      <value>ACQ</value>
      <value>SPBAL-FPAM</value>
      <value>SPBAL-FSAM</value>
      <value>GITL</value>
    </operand>
    <operator>and</operator>
    <operator>and</operator>
  </eng_a>
  <nfov_a>
    <operand keyword="VISTYPE" operator="equals-any">
      <value>CGIVST_TDD_OBS</value>
    </operand>
    <operand keyword="DPAMNAME" operator="contains-any">
      <value>IMAGING</value>
    </operand>
    <operator>and</operator>
    <operand keyword="ISPC" operator="contains-any">
      <value>0</value>
    </operand>
    <operator>and</operator>
    <operand keyword="SPAMNAME" operator="contains-any">
      <value>OPEN</value>
    </operand>
    <operator>and</operator>
    <operand keyword="FRMTYPE" not="true" operator="equals-any">
      <value>ACQ</value>
      <value>SPBAL-FPAM</value>
      <value>SPBAL-FSAM</value>
    </operand>
    <operator>and</operator>
    <operand keyword="FRMTYPE" operator="contains-any">
      <value>CONT</value>
      <value>NUM</value>
    </operand>
    <operator>and</operator>
  </nfov_a>
  <nfov_nc>
    <operand keyword="VISTYPE" operator="equals-any">
      <value>CGIVST_CAL_TGTREF_PHOT</value>
    </operand>
    <operand keyword="DPAMNAME" operator="contains-any">
      <value>IMAGING</value>
    </operand>
    <operator>and</operator>
    <operand keyword="ISPC" operator="contains-any">
      <value>0</value>
    </operand>
   <operand keyword="SPAMNAME" operator="contains-any">
      <value>OPEN</value>
    </operand>
    <operator>and</operator>
    <operator>and</operator>
    <operand keyword="FRMTYPE" not="true" operator="equals-any">
      <value>ACQ</value>
      <value>SPBAL-FPAM</value>
      <value>SPBAL-FSAM</value>
    </operand>
    <operator>and</operator>
    <operand keyword="FRMTYPE" not="true" operator="contains-any">
      <value>CONT</value>
      <value>NUM</value>
    </operand>
    <operator>and</operator>
  </nfov_nc>
  <nfov_pc>
    <operand keyword="VISTYPE" operator="equals-any">
      <value>CGIVST_TDD_OBS</value>
    </operand>
    <operand keyword="DPAMNAME" operator="contains-any">
      <value>IMAGING</value>
    </operand>
    <operator>and</operator>
    <operand keyword="ISPC" operator="contains-any">
      <value>1</value>
    </operand>
    <operator>and</operator>
    <operand keyword="SPAMNAME" operator="contains-any">
      <value>OPEN</value>
    </operand>
    <operator>and</operator>
    <operand keyword="FRMTYPE" not="true" operator="equals-any">
      <value>ACQ</value>
      <value>SPBAL-FPAM</value>
      <value>SPBAL-FSAM</value>
    </operand>
    <operator>and</operator>
    <operand keyword="FRMTYPE" operator="contains-any">
      <value>CONT</value>
      <value>NUM</value>
    </operand>
    <operator>and</operator>
  </nfov_pc>
  <pol_a>
    <operand keyword="VISTYPE" operator="equals-any">
      <value>CGIVST_TDD_POL_OB</value>
    </operand>
    <operand keyword="DPAMNAME" operator="contains-any">
      <value>POL0</value>
      <value>POL45</value>
    </operand>
    <operand keyword="ISPC" operator="contains-any">
      <value>0</value>
    </operand>
    <operand keyword="FRMTYPE" not="true" operator="equals-any">
      <value>ACQ</value>
      <value>SPBAL-FPAM</value>
      <value>SPBAL-FSAM</value>
    </operand>
    <operand keyword="FRMTYPE" operator="contains-any">
      <value>CONT</value>
      <value>NUM</value>
    </operand>
    <operator>and</operator>
    <operator>and</operator>
    <operator>and</operator>
    <operator>and</operator>
  </pol_a>
  <pol_pc>
    <operand keyword="VISTYPE" operator="equals-any">
      <value>CGIVST_TDD_POL_OB</value>
    </operand>
    <operand keyword="DPAMNAME" operator="contains-any">
      <value>POL0</value>
      <value>POL45</value>
    </operand>
    <operand keyword="ISPC" operator="contains-any">
      <value>1</value>
    </operand>
    <operand keyword="FRMTYPE" not="true" operator="equals-any">
      <value>ACQ</value>
      <value>SPBAL-FPAM</value>
      <value>SPBAL-FSAM</value>
    </operand>
    <operand keyword="FRMTYPE" operator="contains-any">
      <value>CONT</value>
      <value>NUM</value>
    </operand>
    <operator>and</operator>
    <operator>and</operator>
    <operator>and</operator>
    <operator>and</operator>
  </pol_pc>
  <spec_a>
    <operand keyword="VISTYPE" operator="equals-any">
      <value>CGIVST_TDD_OBS</value>
    </operand>
    <operand keyword="DPAMNAME" operator="contains-any">
      <value>PRISM2</value>
      <value>PRISM3</value>
    </operand>
    <operand keyword="ISPC" operator="contains-any">
      <value>0</value>
    </operand>
    <operand keyword="FRMTYPE" not="true" operator="equals-any">
      <value>ACQ</value>
      <value>SPBAL-FPAM</value>
      <value>SPBAL-FSAM</value>
    </operand>
    <operand keyword="FRMTYPE" operator="contains-any">
      <value>CONT</value>
      <value>NUM</value>
    </operand>
    <operator>and</operator>
    <operator>and</operator>
    <operator>and</operator>
    <operator>and</operator>
  </spec_a>
  <spec_nc>
    <operand keyword="VISTYPE" operator="equals-any">
